name: CI
on: [ push, workflow_dispatch ]

env:
  NODE_VERSION: 18.14.2

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm lint

      - name: Test
        run: npm test

      - name: Build
        run: npm build
